server:
  port: 8082
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cs304_database
    username: postgres
    password: postgres
  jackson:
    default-property-inclusion: NON_NULL
  jpa:
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.PostgreSQL92Dialect
    show-sql: true
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: true
image-server:
  path: backend/src/main/resources/images
